<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.medical</groupId>
        <artifactId>medical-api</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>medical-knowledge-api</artifactId>
    <name>medical-knowledge-api</name>
    <description>知识库服务 Feign API 定义</description>

    <dependencies>
        <dependency>
            <groupId>com.medical</groupId>
            <artifactId>medical-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
    </dependencies>
</project>